url = https://devhsncu.etranscript.in/#/auth/login
user_name = cost@edulab.in
user_pass = 123456
browser = chrome
filePath = C:\Users\info\Downloads\Solapur.png
excelPath = C:\\Users\\info\\eclipse-workspace\\Framework_Structure_POM_Maven_TestNG Suite\\src\\main\\java\\com\\TestData\\TestData.xlsx

//waits










#We can not Store our Test Data in properties file because properties file are only for Global Environment 
#Here in properties file we use only for Global Environment Variable